todolist_app/urls.py
from django.urls import path  
from .views import TaskList, TaskDetail, TaskCreate, TaskUpdate, TaskDelete, CustomLoginView, CustomLogOutView, TaskRegister
from. import views



app_name = 'todolist_app'
urlpatterns = [
	path('tasklist', TaskList.as_view(), name='tasklist'),
	path('taskcreate/', TaskCreate.as_view(), name='taskcreate'),
	path('task/<int:pk>', TaskDetail.as_view(), name='taskdetail'),
	path('taskupdate/<int:pk>', TaskUpdate.as_view(), name='taskupdate'),
	path('taskdelete/<int:pk>', TaskDelete.as_view(), name='taskdelete'),


	path('login/', CustomLoginView.as_view(), name='login_page'),
	path('logout/', CustomLogOutView.as_view(), name='logout_page'),
	path('register/', TaskRegister.as_view(), name='register'),

	path('home/', views.home, name='home'),
]	



# path('logout/', LogoutView.as_view(next_page='/login/'), name='logout_page')

todolist_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todolist_app.urls'))
]

todolist_app/models.py
from django.db import models
from django.contrib.auth.models import User  

# Create your models here.


class Task(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
	title = models.CharField(max_length=100, null=True)
	description = models.TextField(null=True, blank=True)
	complete = models.BooleanField(default=False)
	created = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.title  

	class Meta:
		ordering = ['complete']

todolist_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import FormView
from django.contrib.auth import login

from django.urls import reverse_lazy
from .models import Task

class TaskList(LoginRequiredMixin, ListView):
	model = Task
	context_object_name = 'tasks'	

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['tasks'] = context['tasks'].filter(user=self.request.user)
		context['count'] = context['tasks'].filter(complete=False).count()

		search_input = self.request.GET.get('search-area') or ''
		if search_input:
			context['tasks'] = context['tasks'].filter(title__icontains=search_input)
			context['search_input'] = search_input


		return context

class TaskDetail(LoginRequiredMixin, DetailView):
	model = Task 
	context_object_name = 'tasks'
	# how to change the name of the template
	# template_name = 'todolist_app/name.html'



class TaskCreate(LoginRequiredMixin, CreateView):
	model = Task 
	fields = ['title', 'description', 'complete']
	success_url = reverse_lazy('todolist_app:tasklist')

	def form_valid(self, form):
		form.instance.user =self.request.user
		return super(TaskCreate, self).form_valid(form)


class TaskUpdate(LoginRequiredMixin, UpdateView):
	model = Task 
	fields = ['title', 'description', 'complete']
	success_url = reverse_lazy('todolist_app:tasklist')



class TaskDelete(LoginRequiredMixin, DeleteView):
	model = Task
	context_object_name = 'tasks'
	success_url = reverse_lazy('todolist_app:tasklist')



class CustomLoginView(LoginView):
	template_name = 'todolist_app/login_page.html'
	fields = '__all__'
	redirect_authenticated_user = False

	def get_success_url(self):
		return reverse_lazy('todolist_app:tasklist')



class CustomLogOutView(LogoutView):
	template_name = 'todolist_app/logout_page.html'

	def get_success_url(self):
		return reverse_lazy('todolist_app:logout_page')


class TaskRegister(FormView):
	template_name = 'todolist_app/register.html'
	form_class = UserCreationForm
	redirect_authenticated_user = True
	success_url = reverse_lazy('todolist_app:login_page')
	
	def form_valid(self, form):
		user = form.save()
		if user is not None:
			login(self.request, user)
		return super(TaskRegister, self).form_valid(form)

	def get(self, *args, **kwargs):
		if self.request.user.is_authenticated:
			return redirect('todolist_app:tasklist')
		return super(TaskRegister, self).get(*args, **kwargs)



def home(request):
	return render(request, 'todolist_app/home.html')

todolist_app/templates/todolist_app/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}Base{% endblock %}</title>

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</head>
<body>
	{% load crispy_forms_tags %}
	


	{% block content %}
	<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="#">Django ToDoList with User Registration</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    
	   	<div class="d-flex navbar-nav" id="navbarNavAltMarkup">
	   		<a class="nav-link" href="#">Home</a>
	        <a class="nav-link" href="#">Profile</a>
	        <a class="nav-link" href="#">LogIn</a>
	        <a class="nav-link" href="#">SignUp</a>

    	</div>
	  </div>
	</nav>
	<div class="container" style="padding-top: 50px;">
		<h1>BASE TEMPLATE</h1>		
	</div>
	
	{% endblock %}
</body>
</html>

todolist_app/templates/todolist_app/home.html
{% extends 'todolist_app/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
	<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="{% url 'todolist_app:home' %}">Django ToDoList with User Registration</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    
	   	<div class="d-flex navbar-nav" id="navbarNavAltMarkup">
	   		<a class="nav-link active" href="{% url 'todolist_app:home' %}">Home</a>
	        <a class="nav-link" href="{% url 'todolist_app:tasklist' %}">TaskList</a>
	        

	        {% if user.is_authenticated %}
	        	<a class="nav-link" href="{% url 'todolist_app:logout_page' %}">Logout</a>
	        {% else %}
	        	<a class="nav-link" href="{% url 'todolist_app:login_page' %}">LogIn</a>
	        	<a class="nav-link" href="{% url 'todolist_app:register' %}">SignUp</a>
	        {% endif %}


    	</div>
	  </div>
	</nav>

	<div class="container" style="padding-top: 60px;">
		<h1>HOME</h1>
		<hr>

		<div>
			<h1>Django Project</h1>
			<h3>To-Do App with User Registration</h3>
			<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Django_logo.svg/1024px-Django_logo.svg.png">
		</div>
	</div>

{% endblock %}

todolist_app/templates/todolist_app/login_page.html
{% extends 'todolist_app/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
	<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="{% url 'todolist_app:home' %}">Django ToDoList with User Registration</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    
	   	<div class="d-flex navbar-nav" id="navbarNavAltMarkup">
	   		<a class="nav-link active" href="{% url 'todolist_app:home' %}">Home</a>
	        <a class="nav-link" href="{% url 'todolist_app:tasklist' %}">TaskList</a>
	        <a class="nav-link" href="{% url 'todolist_app:login_page' %}">LogIn</a>
	        <a class="nav-link" href="{% url 'todolist_app:register' %}">SignUp</a>

    	</div>
	  </div>
	</nav>

	<div class="container" style="padding-top: 60px;">
		<h1>LogIn</h1>
		<hr>
	
		<form method="POST">
			{% csrf_token %}
				<table>
				{{form.as_table}}
				</table>
				<p></p>
				<input type="submit" name="submit" value="LogIn">
				<p></p>
		
			<p>Dont have an account yet? <a href="{% url 'todolist_app:register' %}">Register</a></p>
		</form>
	</div>
{% endblock %}

todolist_app/templates/todolist_app/logout_page.html
{% extends 'todolist_app/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
	<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="{% url 'todolist_app:home' %}">Django ToDoList with User Registration</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    
	   	<div class="d-flex navbar-nav" id="navbarNavAltMarkup">
	   		<a class="nav-link active" href="{% url 'todolist_app:home' %}">Home</a>
	        <a class="nav-link" href="{% url 'todolist_app:tasklist' %}">TaskList</a>
	        <a class="nav-link" href="{% url 'todolist_app:login_page' %}">LogIn</a>
	        <a class="nav-link" href="{% url 'todolist_app:register' %}">SignUp</a>

    	</div>
	  </div>
	</nav>

	<div class="container" style="padding-top: 60px;">
		<h1>Logged Out</h1>
		<hr>
		<a href="{% url 'todolist_app:login_page' %}">LogIn again?</a>
	</div>

{% endblock %}

todolist_app/templates/todolist_app/register.html
{% extends 'todolist_app/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
	<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="{% url 'todolist_app:home' %}">Django ToDoList with User Registration</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    
	   	<div class="d-flex navbar-nav" id="navbarNavAltMarkup">
	   		<a class="nav-link active" href="{% url 'todolist_app:home' %}">Home</a>
	        <a class="nav-link" href="{% url 'todolist_app:tasklist' %}">TaskList</a>
	        <a class="nav-link" href="{% url 'todolist_app:login_page' %}">LogIn</a>
	        <a class="nav-link" href="{% url 'todolist_app:register' %}">SignUp</a>

    	</div>
	  </div>
	</nav>

	<div class="container" style="padding-top: 60px;">
		<h1>Sign Up</h1>
		<hr>
	
		<form method="POST">
			{% csrf_token %}
				<table>
					{{form.as_table}}
				</table>
				<p></p>
				<input type="submit" name="submit" value="SignUp">
				<p></p>
			<p>Already have an account? <a href="{% url 'todolist_app:login_page' %}">LogIn</a></p>
		</form>

	</div>

{% endblock %}

todolist_app/templates/todolist_app/task_confirm_delete.html
{% extends 'todolist_app/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
	<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="{% url 'todolist_app:home' %}">Django ToDoList with User Registration</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    
	   	<div class="d-flex navbar-nav" id="navbarNavAltMarkup">
	   		<a class="nav-link active" href="{% url 'todolist_app:home' %}">Home</a>
	        <a class="nav-link" href="{% url 'todolist_app:tasklist' %}">TaskList</a>
	        <a class="nav-link" href="{% url 'todolist_app:login_page' %}">LogIn</a>
	        <a class="nav-link" href="{% url 'todolist_app:register' %}">SignUp</a>

    	</div>
	  </div>
	</nav>

	<div class="container" style="padding-top: 60px;">
		<h1>Confirm Deletion</h1>
		<hr>

		<form method="POST">
			{% csrf_token %}
		
			<p>Area you sure you want to delete task: {{task}}</p>
			<input type="submit" name="submit" value="Yes, delete it">
		</form>
		<a href="{% url 'todolist_app:tasklist' %}">No, Go back to tasklist</a>
	</div>

{% endblock %}

todolist_app/templates/todolist_app/task_detail.html
{% extends 'todolist_app/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
	<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="{% url 'todolist_app:home' %}">Django ToDoList with User Registration</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    
	   	<div class="d-flex navbar-nav" id="navbarNavAltMarkup">
	   		<a class="nav-link active" href="{% url 'todolist_app:home' %}">Home</a>
	        <a class="nav-link" href="{% url 'todolist_app:tasklist' %}">TaskList</a>
	        <a class="nav-link" href="{% url 'todolist_app:login_page' %}">LogIn</a>
	        <a class="nav-link" href="{% url 'todolist_app:register' %}">SignUp</a>

    	</div>
	  </div>
	</nav>

	<div class="container" style="padding-top: 60px;">
		<h1>TASKS</h1>
		<hr>
		<h1>Task: {{ tasks }}</h1>
	</div>

{% endblock %}


<h1>Task: {{ tasks }}</h1>

todolist_app/templates/todolist_app/task_form.html
{% extends 'todolist_app/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
	<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="{% url 'todolist_app:home' %}">Django ToDoList with User Registration</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    
	   	<div class="d-flex navbar-nav" id="navbarNavAltMarkup">
	   		<a class="nav-link active" href="{% url 'todolist_app:home' %}">Home</a>
	        <a class="nav-link" href="{% url 'todolist_app:tasklist' %}">TaskList</a>
	        <a class="nav-link" href="{% url 'todolist_app:login_page' %}">LogIn</a>
	        <a class="nav-link" href="{% url 'todolist_app:register' %}">SignUp</a>

    	</div>
	  </div>
	</nav>

	<div class="container" style="padding-top: 60px;">
		<h1>TASK FORM</h1>
		<hr>

		<form method='POST'>
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" name="submit" value="Submit">
		
		</form>

		<a href="{% url 'todolist_app:tasklist' %}">Go back to Task List</a>
	</div>

{% endblock %}

todolist_app/templates/todolist_app/task_list.html
{% extends 'todolist_app/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
	<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="{% url 'todolist_app:home' %}">Django ToDoList with User Registration</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    
	   	<div class="d-flex navbar-nav" id="navbarNavAltMarkup">
	   		<a class="nav-link" href="{% url 'todolist_app:home' %}">Home</a>
	        <a class="nav-link active" href="{% url 'todolist_app:tasklist' %}">TaskList</a>
	        <a class="nav-link" href="{% url 'todolist_app:logout_page' %}">LogOut</a>
    	</div>
	  </div>
	</nav>

	<div class="container" style="padding-top: 60px;">
		<h1>TASKLIST</h1>
		<h4>User: {{request.user}}</h4>
		<hr>

		<form method="GET">
			<input type="text" name="search-area">
			<input type="submit" value="Search">
		</form>

		<table>
			
			<tr>
				<th>Items</th>
			</tr>
			{% for task in tasks %}
				<tr>
					<td><strong>{{task.title}}</strong></td>
					<td style="padding-left: 50px;"><button class="btn btn-warning" href="{% url 'todolist_app:taskdetail' task.id %}">View</button></td>
					<td><button class="btn btn-success" href="{% url 'todolist_app:taskupdate' task.id %}">Update</button></td>
					<td><button class="btn btn-danger" href="{% url 'todolist_app:taskdelete' task.id %}">Delete</button></td>
		
				</tr>
				{% empty %}
					<h1>No Item In the List</h1>
			{% endfor %}
		
		
		</table>



		<button class="btn btn-success" href="{% url 'todolist_app:taskcreate' %}">Add New Task</button>
	</div>

{% endblock %}